#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DropboxApp.Resource", IsApplication=true)]

namespace DropboxApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_centre = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int rotate_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int shadow = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int shadowMax = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000f
			public const int autoScaleTextViewStyle = 2130771983;
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010010
			public const int minTextSize = 2130771984;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010011
			public const int shrinkTextSize = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070004
			public const int air_force_blue = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int algae_green = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int alice_blue = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int alien_green = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int almond = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int amber = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int american_rose = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int amethyst = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int android_green = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int anti_flash_white = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int antique_brass = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int antique_fuchsia = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int antique_white = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int apple_green = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int apricot = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int aqua = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int aqua_marine = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int army_brown = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int army_green = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int ash_grey = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int asparagus = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int atomic_tangerine = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int aureolin = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int aurometalsaurus = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int avocado_green = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int awesome = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int aztech_purple = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int azure = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int azure_mist_web = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int baby_blue = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int baby_blue_eyes = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int baby_pink = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int ball_blue = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int banana_mania = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int banana_yellow = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int bashful_pink = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int basket_ball_orange = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int battleship_grey = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int bazaar = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int bean_red = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int beaver = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int bee_yellow = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int beer = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int beetle_green = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int beige = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int bisque = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int bistre = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int bittersweet = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int black = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int black_cat = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int black_cow = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int black_eel = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int blanched_almond = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int blanchedalmond = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int bleu_de_france = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int blizzard_blue = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int blond = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int blood_red = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int blossom_pink = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int blue = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int blue_angel = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int blue_bell = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int blue_diamond = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int blue_dress = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int blue_eyes = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int blue_gray = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int blue_green = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int blue_hosta = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int blue_ivy = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int blue_jay = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int blue_koi = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int blue_lagoon = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int blue_lotus = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int blue_orchid = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int blue_purple = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int blue_ribbon = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int blue_whale = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int blue_zircon = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int blueberry_blue = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int blush = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int blush_pink = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int blush_red = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int bole = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int bondi_blue = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int bone = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int bottle_green = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int boysenberry = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int brandeis_blue = 2131165275;
			
			// aapt resource value: 0x7f07005c
			public const int brass = 2131165276;
			
			// aapt resource value: 0x7f07005d
			public const int brick_red = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int bright_cerulean = 2131165278;
			
			// aapt resource value: 0x7f07005f
			public const int bright_gold = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int bright_green = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int bright_lavender = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int bright_maroon = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int bright_neon_pink = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int bright_pink = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int bright_turquoise = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int bright_ube = 2131165286;
			
			// aapt resource value: 0x7f070067
			public const int brilliant_lavender = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int brilliant_rose = 2131165288;
			
			// aapt resource value: 0x7f070069
			public const int brink_pink = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int british_racing_green = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int bronze = 2131165291;
			
			// aapt resource value: 0x7f07006c
			public const int brown_bear = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int brown_sugar = 2131165293;
			
			// aapt resource value: 0x7f07006e
			public const int bubble_gum = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int bubbles = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int buff = 2131165296;
			
			// aapt resource value: 0x7f070071
			public const int bulgarian_rose = 2131165297;
			
			// aapt resource value: 0x7f070072
			public const int burgundy = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int burlywood = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int burnt_orange = 2131165300;
			
			// aapt resource value: 0x7f070075
			public const int burnt_pink = 2131165301;
			
			// aapt resource value: 0x7f070076
			public const int burnt_sienna = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int burnt_umber = 2131165303;
			
			// aapt resource value: 0x7f070078
			public const int butterfly_blue = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int byzantine = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int byzantium = 2131165306;
			
			// aapt resource value: 0x7f07007b
			public const int cadet = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int cadet_blue = 2131165308;
			
			// aapt resource value: 0x7f07007d
			public const int cadet_grey = 2131165309;
			
			// aapt resource value: 0x7f07007e
			public const int cadillac_pink = 2131165310;
			
			// aapt resource value: 0x7f07007f
			public const int cadmium_green = 2131165311;
			
			// aapt resource value: 0x7f070080
			public const int cadmium_orange = 2131165312;
			
			// aapt resource value: 0x7f070081
			public const int cadmium_red = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int cadmium_yellow = 2131165314;
			
			// aapt resource value: 0x7f070083
			public const int cafe_noir = 2131165315;
			
			// aapt resource value: 0x7f070084
			public const int cal_poly_pomona_green = 2131165316;
			
			// aapt resource value: 0x7f070085
			public const int cambridge_blue = 2131165317;
			
			// aapt resource value: 0x7f070086
			public const int camel_brown = 2131165318;
			
			// aapt resource value: 0x7f070087
			public const int camouflage_green = 2131165319;
			
			// aapt resource value: 0x7f070088
			public const int canary = 2131165320;
			
			// aapt resource value: 0x7f070089
			public const int canary_yellow = 2131165321;
			
			// aapt resource value: 0x7f07008a
			public const int candy_apple_red = 2131165322;
			
			// aapt resource value: 0x7f07008b
			public const int candy_pink = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int cantaloupe = 2131165324;
			
			// aapt resource value: 0x7f07008d
			public const int capri = 2131165325;
			
			// aapt resource value: 0x7f07008e
			public const int caput_mortuum = 2131165326;
			
			// aapt resource value: 0x7f07008f
			public const int caramel = 2131165327;
			
			// aapt resource value: 0x7f070090
			public const int carbon_gray = 2131165328;
			
			// aapt resource value: 0x7f070091
			public const int cardinal = 2131165329;
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			// aapt resource value: 0x7f070092
			public const int caribbean_green = 2131165330;
			
			// aapt resource value: 0x7f070093
			public const int carmine = 2131165331;
			
			// aapt resource value: 0x7f070094
			public const int carmine_pink = 2131165332;
			
			// aapt resource value: 0x7f070095
			public const int carmine_red = 2131165333;
			
			// aapt resource value: 0x7f070096
			public const int carnation_pink_one = 2131165334;
			
			// aapt resource value: 0x7f070097
			public const int carnation_pink_three = 2131165335;
			
			// aapt resource value: 0x7f070098
			public const int carnation_pink_two = 2131165336;
			
			// aapt resource value: 0x7f070099
			public const int carolina_blue = 2131165337;
			
			// aapt resource value: 0x7f07009a
			public const int carrot_orange = 2131165338;
			
			// aapt resource value: 0x7f07009b
			public const int celadon = 2131165339;
			
			// aapt resource value: 0x7f07009c
			public const int celeste = 2131165340;
			
			// aapt resource value: 0x7f07009d
			public const int celestial_blue = 2131165341;
			
			// aapt resource value: 0x7f07009e
			public const int cerise_pink = 2131165342;
			
			// aapt resource value: 0x7f07009f
			public const int cerulean = 2131165343;
			
			// aapt resource value: 0x7f0700a0
			public const int cerulean_blue = 2131165344;
			
			// aapt resource value: 0x7f0700a1
			public const int cg_blue = 2131165345;
			
			// aapt resource value: 0x7f0700a2
			public const int cg_red = 2131165346;
			
			// aapt resource value: 0x7f0700a3
			public const int chamoisee = 2131165347;
			
			// aapt resource value: 0x7f0700a4
			public const int champagne = 2131165348;
			
			// aapt resource value: 0x7f0700a5
			public const int charcoal = 2131165349;
			
			// aapt resource value: 0x7f0700a6
			public const int chartreuse = 2131165350;
			
			// aapt resource value: 0x7f0700a7
			public const int cherry = 2131165351;
			
			// aapt resource value: 0x7f0700a8
			public const int cherry_blossom_pink = 2131165352;
			
			// aapt resource value: 0x7f0700a9
			public const int cherry_red = 2131165353;
			
			// aapt resource value: 0x7f0700aa
			public const int chestnut = 2131165354;
			
			// aapt resource value: 0x7f0700ab
			public const int chestnut_red = 2131165355;
			
			// aapt resource value: 0x7f0700ac
			public const int chilli_pepper = 2131165356;
			
			// aapt resource value: 0x7f0700ad
			public const int chocolate = 2131165357;
			
			// aapt resource value: 0x7f0700ae
			public const int chrome_yellow = 2131165358;
			
			// aapt resource value: 0x7f0700af
			public const int cinereous = 2131165359;
			
			// aapt resource value: 0x7f0700b0
			public const int cinnabar = 2131165360;
			
			// aapt resource value: 0x7f0700b1
			public const int citrine = 2131165361;
			
			// aapt resource value: 0x7f0700b2
			public const int classic_rose = 2131165362;
			
			// aapt resource value: 0x7f0700b3
			public const int cloudy_gray = 2131165363;
			
			// aapt resource value: 0x7f0700b4
			public const int clover_green = 2131165364;
			
			// aapt resource value: 0x7f0700b5
			public const int cobalt = 2131165365;
			
			// aapt resource value: 0x7f0700b6
			public const int cobalt_blue = 2131165366;
			
			// aapt resource value: 0x7f0700b7
			public const int coffee = 2131165367;
			
			// aapt resource value: 0x7f0700b8
			public const int columbia_blue = 2131165368;
			
			// aapt resource value: 0x7f0700b9
			public const int construction_cone_orange = 2131165369;
			
			// aapt resource value: 0x7f0700ba
			public const int cookie_brown = 2131165370;
			
			// aapt resource value: 0x7f0700bb
			public const int cool_black = 2131165371;
			
			// aapt resource value: 0x7f0700bc
			public const int cool_grey = 2131165372;
			
			// aapt resource value: 0x7f0700bd
			public const int copper = 2131165373;
			
			// aapt resource value: 0x7f0700be
			public const int copper_rose = 2131165374;
			
			// aapt resource value: 0x7f0700bf
			public const int coquelicot = 2131165375;
			
			// aapt resource value: 0x7f0700c0
			public const int coral = 2131165376;
			
			// aapt resource value: 0x7f0700c1
			public const int coral_blue = 2131165377;
			
			// aapt resource value: 0x7f0700c2
			public const int coral_pink = 2131165378;
			
			// aapt resource value: 0x7f0700c3
			public const int coral_red = 2131165379;
			
			// aapt resource value: 0x7f0700c4
			public const int cordovan = 2131165380;
			
			// aapt resource value: 0x7f0700c5
			public const int corn = 2131165381;
			
			// aapt resource value: 0x7f0700c6
			public const int corn_yellow = 2131165382;
			
			// aapt resource value: 0x7f0700c7
			public const int cornell_red = 2131165383;
			
			// aapt resource value: 0x7f0700c8
			public const int cornflower = 2131165384;
			
			// aapt resource value: 0x7f0700c9
			public const int cornflower_blue = 2131165385;
			
			// aapt resource value: 0x7f0700ca
			public const int cornsilk = 2131165386;
			
			// aapt resource value: 0x7f0700cb
			public const int cosmic_latte = 2131165387;
			
			// aapt resource value: 0x7f0700cc
			public const int cotton_candy = 2131165388;
			
			// aapt resource value: 0x7f0700cd
			public const int cranberry = 2131165389;
			
			// aapt resource value: 0x7f0700ce
			public const int cream = 2131165390;
			
			// aapt resource value: 0x7f0700cf
			public const int crimson = 2131165391;
			
			// aapt resource value: 0x7f0700d0
			public const int crimson_glory = 2131165392;
			
			// aapt resource value: 0x7f0700d1
			public const int crimson_red = 2131165393;
			
			// aapt resource value: 0x7f0700d2
			public const int crocus_purple = 2131165394;
			
			// aapt resource value: 0x7f0700d3
			public const int crystal_blue = 2131165395;
			
			// aapt resource value: 0x7f0700d4
			public const int cyan = 2131165396;
			
			// aapt resource value: 0x7f0700d5
			public const int cyan_opaque = 2131165397;
			
			// aapt resource value: 0x7f0700d6
			public const int daffodil = 2131165398;
			
			// aapt resource value: 0x7f0700d7
			public const int dandelion = 2131165399;
			
			// aapt resource value: 0x7f0700d8
			public const int dark_blue = 2131165400;
			
			// aapt resource value: 0x7f0700d9
			public const int dark_brown = 2131165401;
			
			// aapt resource value: 0x7f0700da
			public const int dark_byzantium = 2131165402;
			
			// aapt resource value: 0x7f0700db
			public const int dark_candy_apple_red = 2131165403;
			
			// aapt resource value: 0x7f0700dc
			public const int dark_cerulean = 2131165404;
			
			// aapt resource value: 0x7f0700dd
			public const int dark_chestnut = 2131165405;
			
			// aapt resource value: 0x7f0700de
			public const int dark_coral = 2131165406;
			
			// aapt resource value: 0x7f0700df
			public const int dark_cyan = 2131165407;
			
			// aapt resource value: 0x7f0700e0
			public const int dark_electric_blue = 2131165408;
			
			// aapt resource value: 0x7f0700e1
			public const int dark_forrest_green = 2131165409;
			
			// aapt resource value: 0x7f0700e2
			public const int dark_goldenrod = 2131165410;
			
			// aapt resource value: 0x7f0700e3
			public const int dark_gray = 2131165411;
			
			// aapt resource value: 0x7f0700e4
			public const int dark_green = 2131165412;
			
			// aapt resource value: 0x7f0700e5
			public const int dark_jungle_green = 2131165413;
			
			// aapt resource value: 0x7f0700e6
			public const int dark_khaki = 2131165414;
			
			// aapt resource value: 0x7f0700e7
			public const int dark_lavender = 2131165415;
			
			// aapt resource value: 0x7f0700e8
			public const int dark_magenta = 2131165416;
			
			// aapt resource value: 0x7f0700e9
			public const int dark_midnight_blue = 2131165417;
			
			// aapt resource value: 0x7f0700ea
			public const int dark_olive_green = 2131165418;
			
			// aapt resource value: 0x7f0700eb
			public const int dark_orange = 2131165419;
			
			// aapt resource value: 0x7f0700ec
			public const int dark_orchid = 2131165420;
			
			// aapt resource value: 0x7f0700ed
			public const int dark_pastel_blue = 2131165421;
			
			// aapt resource value: 0x7f0700ee
			public const int dark_pastel_green = 2131165422;
			
			// aapt resource value: 0x7f0700ef
			public const int dark_pastel_purple = 2131165423;
			
			// aapt resource value: 0x7f0700f0
			public const int dark_pastel_red = 2131165424;
			
			// aapt resource value: 0x7f0700f1
			public const int dark_pink = 2131165425;
			
			// aapt resource value: 0x7f0700f2
			public const int dark_powder_blue = 2131165426;
			
			// aapt resource value: 0x7f0700f3
			public const int dark_raspberry = 2131165427;
			
			// aapt resource value: 0x7f0700f4
			public const int dark_red = 2131165428;
			
			// aapt resource value: 0x7f0700f5
			public const int dark_salmon = 2131165429;
			
			// aapt resource value: 0x7f0700f6
			public const int dark_scarlet = 2131165430;
			
			// aapt resource value: 0x7f0700f7
			public const int dark_sea_green = 2131165431;
			
			// aapt resource value: 0x7f0700f8
			public const int dark_sienna = 2131165432;
			
			// aapt resource value: 0x7f0700f9
			public const int dark_slate_blue = 2131165433;
			
			// aapt resource value: 0x7f0700fa
			public const int dark_slate_gray = 2131165434;
			
			// aapt resource value: 0x7f0700fb
			public const int dark_spring_green = 2131165435;
			
			// aapt resource value: 0x7f0700fc
			public const int dark_tan = 2131165436;
			
			// aapt resource value: 0x7f0700fd
			public const int dark_tangerine = 2131165437;
			
			// aapt resource value: 0x7f0700fe
			public const int dark_terra_cotta = 2131165438;
			
			// aapt resource value: 0x7f0700ff
			public const int dark_turquoise = 2131165439;
			
			// aapt resource value: 0x7f070100
			public const int dark_violet = 2131165440;
			
			// aapt resource value: 0x7f070101
			public const int dartmouth_green = 2131165441;
			
			// aapt resource value: 0x7f070102
			public const int davy_grey = 2131165442;
			
			// aapt resource value: 0x7f070103
			public const int debian_red = 2131165443;
			
			// aapt resource value: 0x7f070104
			public const int deep_carmine = 2131165444;
			
			// aapt resource value: 0x7f070105
			public const int deep_carmine_pink = 2131165445;
			
			// aapt resource value: 0x7f070106
			public const int deep_carrot_orange = 2131165446;
			
			// aapt resource value: 0x7f070107
			public const int deep_cerise = 2131165447;
			
			// aapt resource value: 0x7f070108
			public const int deep_champagne = 2131165448;
			
			// aapt resource value: 0x7f070109
			public const int deep_chestnut = 2131165449;
			
			// aapt resource value: 0x7f07010a
			public const int deep_coffee = 2131165450;
			
			// aapt resource value: 0x7f07010b
			public const int deep_fuchsia = 2131165451;
			
			// aapt resource value: 0x7f07010c
			public const int deep_jungle_green = 2131165452;
			
			// aapt resource value: 0x7f07010d
			public const int deep_lilac = 2131165453;
			
			// aapt resource value: 0x7f07010e
			public const int deep_magenta = 2131165454;
			
			// aapt resource value: 0x7f07010f
			public const int deep_peach = 2131165455;
			
			// aapt resource value: 0x7f070110
			public const int deep_pink = 2131165456;
			
			// aapt resource value: 0x7f070111
			public const int deep_saffron = 2131165457;
			
			// aapt resource value: 0x7f070112
			public const int deep_sky_blue = 2131165458;
			
			// aapt resource value: 0x7f070113
			public const int denim = 2131165459;
			
			// aapt resource value: 0x7f070114
			public const int denim_blue = 2131165460;
			
			// aapt resource value: 0x7f070115
			public const int desert_sand = 2131165461;
			
			// aapt resource value: 0x7f070116
			public const int dim_gray = 2131165462;
			
			// aapt resource value: 0x7f070117
			public const int dimorphotheca_magenta = 2131165463;
			
			// aapt resource value: 0x7f070118
			public const int dodger_blue = 2131165464;
			
			// aapt resource value: 0x7f070119
			public const int dogwood_rose = 2131165465;
			
			// aapt resource value: 0x7f07011a
			public const int dollar_bill_green = 2131165466;
			
			// aapt resource value: 0x7f07011b
			public const int dragon_green = 2131165467;
			
			// aapt resource value: 0x7f07011c
			public const int duke_blue = 2131165468;
			
			// aapt resource value: 0x7f07011d
			public const int dull_purple = 2131165469;
			
			// aapt resource value: 0x7f07011e
			public const int earth_blue = 2131165470;
			
			// aapt resource value: 0x7f07011f
			public const int earth_yellow = 2131165471;
			
			// aapt resource value: 0x7f070120
			public const int eggplant = 2131165472;
			
			// aapt resource value: 0x7f070121
			public const int eggshell = 2131165473;
			
			// aapt resource value: 0x7f070122
			public const int egyptian_blue = 2131165474;
			
			// aapt resource value: 0x7f070123
			public const int electric_blue = 2131165475;
			
			// aapt resource value: 0x7f070124
			public const int electric_crimson = 2131165476;
			
			// aapt resource value: 0x7f070125
			public const int electric_green = 2131165477;
			
			// aapt resource value: 0x7f070126
			public const int electric_indigo = 2131165478;
			
			// aapt resource value: 0x7f070127
			public const int electric_lavender = 2131165479;
			
			// aapt resource value: 0x7f070128
			public const int electric_purple = 2131165480;
			
			// aapt resource value: 0x7f070129
			public const int electric_ultramarine = 2131165481;
			
			// aapt resource value: 0x7f07012a
			public const int electric_violet = 2131165482;
			
			// aapt resource value: 0x7f07012b
			public const int emerald = 2131165483;
			
			// aapt resource value: 0x7f07012c
			public const int emerald_green = 2131165484;
			
			// aapt resource value: 0x7f07012d
			public const int eton_blue = 2131165485;
			
			// aapt resource value: 0x7f07012e
			public const int fall_leaf_brown = 2131165486;
			
			// aapt resource value: 0x7f07012f
			public const int falu_red = 2131165487;
			
			// aapt resource value: 0x7f070130
			public const int famous = 2131165488;
			
			// aapt resource value: 0x7f070131
			public const int fandango = 2131165489;
			
			// aapt resource value: 0x7f070132
			public const int fashion_fuchsia = 2131165490;
			
			// aapt resource value: 0x7f070133
			public const int fawn = 2131165491;
			
			// aapt resource value: 0x7f070134
			public const int feldgrau = 2131165492;
			
			// aapt resource value: 0x7f070135
			public const int fern = 2131165493;
			
			// aapt resource value: 0x7f070136
			public const int fern_green = 2131165494;
			
			// aapt resource value: 0x7f070137
			public const int ferrari_red = 2131165495;
			
			// aapt resource value: 0x7f070138
			public const int field_drab = 2131165496;
			
			// aapt resource value: 0x7f070139
			public const int fire_engine_red = 2131165497;
			
			// aapt resource value: 0x7f07013a
			public const int firebrick = 2131165498;
			
			// aapt resource value: 0x7f07013b
			public const int flame = 2131165499;
			
			// aapt resource value: 0x7f07013c
			public const int flamingo_pink = 2131165500;
			
			// aapt resource value: 0x7f07013d
			public const int flavescent = 2131165501;
			
			// aapt resource value: 0x7f07013e
			public const int flax = 2131165502;
			
			// aapt resource value: 0x7f07013f
			public const int floral_white = 2131165503;
			
			// aapt resource value: 0x7f070140
			public const int fluorescent_pink = 2131165504;
			
			// aapt resource value: 0x7f070141
			public const int fluorescent_yellow = 2131165505;
			
			// aapt resource value: 0x7f070142
			public const int folly = 2131165506;
			
			// aapt resource value: 0x7f070143
			public const int forest_green = 2131165507;
			
			// aapt resource value: 0x7f070144
			public const int french_beige = 2131165508;
			
			// aapt resource value: 0x7f070145
			public const int french_blue = 2131165509;
			
			// aapt resource value: 0x7f070146
			public const int french_lilac = 2131165510;
			
			// aapt resource value: 0x7f070147
			public const int french_rose = 2131165511;
			
			// aapt resource value: 0x7f070148
			public const int frog_green = 2131165512;
			
			// aapt resource value: 0x7f070149
			public const int fuchsia = 2131165513;
			
			// aapt resource value: 0x7f07014a
			public const int fuchsia_pink = 2131165514;
			
			// aapt resource value: 0x7f07014b
			public const int fulvous = 2131165515;
			
			// aapt resource value: 0x7f07014c
			public const int fuzzy_wuzzy = 2131165516;
			
			// aapt resource value: 0x7f07014d
			public const int gainsboro = 2131165517;
			
			// aapt resource value: 0x7f07014e
			public const int gamboge = 2131165518;
			
			// aapt resource value: 0x7f07014f
			public const int ghost_white = 2131165519;
			
			// aapt resource value: 0x7f070150
			public const int ginger = 2131165520;
			
			// aapt resource value: 0x7f070151
			public const int ginger_brown = 2131165521;
			
			// aapt resource value: 0x7f070152
			public const int glaucous = 2131165522;
			
			// aapt resource value: 0x7f070153
			public const int glitter = 2131165523;
			
			// aapt resource value: 0x7f070154
			public const int gold = 2131165524;
			
			// aapt resource value: 0x7f070155
			public const int golden = 2131165525;
			
			// aapt resource value: 0x7f070156
			public const int golden_brown = 2131165526;
			
			// aapt resource value: 0x7f070157
			public const int golden_poppy = 2131165527;
			
			// aapt resource value: 0x7f070158
			public const int golden_yellow = 2131165528;
			
			// aapt resource value: 0x7f070159
			public const int goldenrod = 2131165529;
			
			// aapt resource value: 0x7f07015a
			public const int granite = 2131165530;
			
			// aapt resource value: 0x7f07015b
			public const int granny_smith_apple = 2131165531;
			
			// aapt resource value: 0x7f07015c
			public const int grape = 2131165532;
			
			// aapt resource value: 0x7f07015d
			public const int grapefruit = 2131165533;
			
			// aapt resource value: 0x7f07015e
			public const int gray_asparagus = 2131165534;
			
			// aapt resource value: 0x7f07015f
			public const int gray_cloud = 2131165535;
			
			// aapt resource value: 0x7f070160
			public const int gray_dolphin = 2131165536;
			
			// aapt resource value: 0x7f070161
			public const int gray_goose = 2131165537;
			
			// aapt resource value: 0x7f070162
			public const int gray_wolf = 2131165538;
			
			// aapt resource value: 0x7f070163
			public const int grayish_turquoise = 2131165539;
			
			// aapt resource value: 0x7f070164
			public const int green_apple = 2131165540;
			
			// aapt resource value: 0x7f070165
			public const int green_blue = 2131165541;
			
			// aapt resource value: 0x7f070166
			public const int green_onion = 2131165542;
			
			// aapt resource value: 0x7f070167
			public const int green_peas = 2131165543;
			
			// aapt resource value: 0x7f070168
			public const int green_snake = 2131165544;
			
			// aapt resource value: 0x7f070169
			public const int green_thumb = 2131165545;
			
			// aapt resource value: 0x7f07016a
			public const int green_yellow = 2131165546;
			
			// aapt resource value: 0x7f07016b
			public const int greenish_blue = 2131165547;
			
			// aapt resource value: 0x7f07016c
			public const int grey = 2131165548;
			
			// aapt resource value: 0x7f07016d
			public const int grullo = 2131165549;
			
			// aapt resource value: 0x7f07016e
			public const int gunmetal = 2131165550;
			
			// aapt resource value: 0x7f07016f
			public const int guppie_green = 2131165551;
			
			// aapt resource value: 0x7f070170
			public const int halaya_ube = 2131165552;
			
			// aapt resource value: 0x7f070171
			public const int halloween_orange = 2131165553;
			
			// aapt resource value: 0x7f070172
			public const int han_blue = 2131165554;
			
			// aapt resource value: 0x7f070173
			public const int han_purple = 2131165555;
			
			// aapt resource value: 0x7f070174
			public const int hansa_yellow = 2131165556;
			
			// aapt resource value: 0x7f070175
			public const int harlequin = 2131165557;
			
			// aapt resource value: 0x7f070176
			public const int harvard_crimson = 2131165558;
			
			// aapt resource value: 0x7f070177
			public const int harvest_gold = 2131165559;
			
			// aapt resource value: 0x7f070178
			public const int hazel_green = 2131165560;
			
			// aapt resource value: 0x7f070179
			public const int heliotrope = 2131165561;
			
			// aapt resource value: 0x7f07017a
			public const int heliotrope_purple = 2131165562;
			
			// aapt resource value: 0x7f07017b
			public const int hollywood_cerise = 2131165563;
			
			// aapt resource value: 0x7f07017c
			public const int honeydew = 2131165564;
			
			// aapt resource value: 0x7f07017d
			public const int hooker_green = 2131165565;
			
			// aapt resource value: 0x7f07017e
			public const int hot_magenta = 2131165566;
			
			// aapt resource value: 0x7f07017f
			public const int hot_pink = 2131165567;
			
			// aapt resource value: 0x7f070180
			public const int hummingbird_green = 2131165568;
			
			// aapt resource value: 0x7f070181
			public const int hunter_green = 2131165569;
			
			// aapt resource value: 0x7f070182
			public const int iceberg = 2131165570;
			
			// aapt resource value: 0x7f070183
			public const int icterine = 2131165571;
			
			// aapt resource value: 0x7f070184
			public const int iguana_green = 2131165572;
			
			// aapt resource value: 0x7f070185
			public const int inchworm = 2131165573;
			
			// aapt resource value: 0x7f070186
			public const int india_green = 2131165574;
			
			// aapt resource value: 0x7f070187
			public const int indian_yellow = 2131165575;
			
			// aapt resource value: 0x7f070188
			public const int indigo = 2131165576;
			
			// aapt resource value: 0x7f070189
			public const int international_klein_blue = 2131165577;
			
			// aapt resource value: 0x7f07018a
			public const int international_orange = 2131165578;
			
			// aapt resource value: 0x7f07018b
			public const int iris = 2131165579;
			
			// aapt resource value: 0x7f07018c
			public const int isabelline = 2131165580;
			
			// aapt resource value: 0x7f07018d
			public const int islamic_green = 2131165581;
			
			// aapt resource value: 0x7f07018e
			public const int ivory = 2131165582;
			
			// aapt resource value: 0x7f07018f
			public const int jade = 2131165583;
			
			// aapt resource value: 0x7f070190
			public const int jasmine = 2131165584;
			
			// aapt resource value: 0x7f070191
			public const int jasmine_purple = 2131165585;
			
			// aapt resource value: 0x7f070192
			public const int jasper = 2131165586;
			
			// aapt resource value: 0x7f070193
			public const int jazzberry_jam = 2131165587;
			
			// aapt resource value: 0x7f070194
			public const int jeans_blue = 2131165588;
			
			// aapt resource value: 0x7f070195
			public const int jellyfish = 2131165589;
			
			// aapt resource value: 0x7f070196
			public const int jet_gray = 2131165590;
			
			// aapt resource value: 0x7f070197
			public const int jonquil = 2131165591;
			
			// aapt resource value: 0x7f070198
			public const int june_bud = 2131165592;
			
			// aapt resource value: 0x7f070199
			public const int jungle_green = 2131165593;
			
			// aapt resource value: 0x7f07019a
			public const int kelly_green = 2131165594;
			
			// aapt resource value: 0x7f07019b
			public const int khaki = 2131165595;
			
			// aapt resource value: 0x7f07019c
			public const int khaki_rose = 2131165596;
			
			// aapt resource value: 0x7f07019d
			public const int ku_crimson = 2131165597;
			
			// aapt resource value: 0x7f07019e
			public const int la_salle_green = 2131165598;
			
			// aapt resource value: 0x7f07019f
			public const int languid_lavender = 2131165599;
			
			// aapt resource value: 0x7f0701a0
			public const int lapis_blue = 2131165600;
			
			// aapt resource value: 0x7f0701a1
			public const int lapis_lazuli = 2131165601;
			
			// aapt resource value: 0x7f0701a2
			public const int laser_lemon = 2131165602;
			
			// aapt resource value: 0x7f0701a3
			public const int laurel_green = 2131165603;
			
			// aapt resource value: 0x7f0701a4
			public const int lava = 2131165604;
			
			// aapt resource value: 0x7f0701a5
			public const int lava_red = 2131165605;
			
			// aapt resource value: 0x7f0701a6
			public const int lavender = 2131165606;
			
			// aapt resource value: 0x7f0701a7
			public const int lavender_blue = 2131165607;
			
			// aapt resource value: 0x7f0701a8
			public const int lavender_blush = 2131165608;
			
			// aapt resource value: 0x7f0701a9
			public const int lavender_gray = 2131165609;
			
			// aapt resource value: 0x7f0701aa
			public const int lavender_indigo = 2131165610;
			
			// aapt resource value: 0x7f0701ab
			public const int lavender_magenta = 2131165611;
			
			// aapt resource value: 0x7f0701ac
			public const int lavender_pink = 2131165612;
			
			// aapt resource value: 0x7f0701ad
			public const int lavender_pinocchio = 2131165613;
			
			// aapt resource value: 0x7f0701ae
			public const int lavender_purple = 2131165614;
			
			// aapt resource value: 0x7f0701af
			public const int lavender_rose = 2131165615;
			
			// aapt resource value: 0x7f0701b0
			public const int lawn_green = 2131165616;
			
			// aapt resource value: 0x7f0701b1
			public const int lemon = 2131165617;
			
			// aapt resource value: 0x7f0701b2
			public const int lemon_chiffon = 2131165618;
			
			// aapt resource value: 0x7f0701b3
			public const int lemon_lime = 2131165619;
			
			// aapt resource value: 0x7f0701b4
			public const int lemon_yellow = 2131165620;
			
			// aapt resource value: 0x7f0701b5
			public const int light_apricot = 2131165621;
			
			// aapt resource value: 0x7f0701b6
			public const int light_aquamarine = 2131165622;
			
			// aapt resource value: 0x7f0701b7
			public const int light_blue = 2131165623;
			
			// aapt resource value: 0x7f0701b8
			public const int light_brown = 2131165624;
			
			// aapt resource value: 0x7f0701b9
			public const int light_carmine_pink = 2131165625;
			
			// aapt resource value: 0x7f0701ba
			public const int light_coral = 2131165626;
			
			// aapt resource value: 0x7f0701bb
			public const int light_cornflower_blue = 2131165627;
			
			// aapt resource value: 0x7f0701bc
			public const int light_crimson = 2131165628;
			
			// aapt resource value: 0x7f0701bd
			public const int light_cyan = 2131165629;
			
			// aapt resource value: 0x7f0701be
			public const int light_fuchsia_pink = 2131165630;
			
			// aapt resource value: 0x7f0701bf
			public const int light_goldenrod_yellow = 2131165631;
			
			// aapt resource value: 0x7f0701c0
			public const int light_gray = 2131165632;
			
			// aapt resource value: 0x7f0701c1
			public const int light_green = 2131165633;
			
			// aapt resource value: 0x7f0701c2
			public const int light_jade = 2131165634;
			
			// aapt resource value: 0x7f0701c3
			public const int light_khaki = 2131165635;
			
			// aapt resource value: 0x7f0701c4
			public const int light_pastel_purple = 2131165636;
			
			// aapt resource value: 0x7f0701c5
			public const int light_pink = 2131165637;
			
			// aapt resource value: 0x7f0701c6
			public const int light_salmon = 2131165638;
			
			// aapt resource value: 0x7f0701c7
			public const int light_salmon_pink = 2131165639;
			
			// aapt resource value: 0x7f0701c8
			public const int light_sea_green = 2131165640;
			
			// aapt resource value: 0x7f0701c9
			public const int light_sky_blue = 2131165641;
			
			// aapt resource value: 0x7f0701ca
			public const int light_slate = 2131165642;
			
			// aapt resource value: 0x7f0701cb
			public const int light_slate_blue = 2131165643;
			
			// aapt resource value: 0x7f0701cc
			public const int light_slate_gray = 2131165644;
			
			// aapt resource value: 0x7f0701cd
			public const int light_steel_blue = 2131165645;
			
			// aapt resource value: 0x7f0701ce
			public const int light_taupe = 2131165646;
			
			// aapt resource value: 0x7f0701cf
			public const int light_thulian_pink = 2131165647;
			
			// aapt resource value: 0x7f0701d0
			public const int light_yellow = 2131165648;
			
			// aapt resource value: 0x7f0701d1
			public const int lilac = 2131165649;
			
			// aapt resource value: 0x7f0701d2
			public const int lime_green = 2131165650;
			
			// aapt resource value: 0x7f0701d3
			public const int lincoln_green = 2131165651;
			
			// aapt resource value: 0x7f0701d4
			public const int linen = 2131165652;
			
			// aapt resource value: 0x7f0701d5
			public const int lipstick_pink = 2131165653;
			
			// aapt resource value: 0x7f0701d6
			public const int liver = 2131165654;
			
			// aapt resource value: 0x7f0701d7
			public const int love_red = 2131165655;
			
			// aapt resource value: 0x7f0701d8
			public const int lovely_purple = 2131165656;
			
			// aapt resource value: 0x7f0701d9
			public const int lust = 2131165657;
			
			// aapt resource value: 0x7f0701da
			public const int macaroni_and_cheese = 2131165658;
			
			// aapt resource value: 0x7f0701db
			public const int magenta = 2131165659;
			
			// aapt resource value: 0x7f0701dc
			public const int magic_mint = 2131165660;
			
			// aapt resource value: 0x7f0701dd
			public const int magnolia = 2131165661;
			
			// aapt resource value: 0x7f0701de
			public const int mahogany = 2131165662;
			
			// aapt resource value: 0x7f0701df
			public const int maize = 2131165663;
			
			// aapt resource value: 0x7f0701e0
			public const int majorelle_blue = 2131165664;
			
			// aapt resource value: 0x7f0701e1
			public const int malachite = 2131165665;
			
			// aapt resource value: 0x7f0701e2
			public const int manatee = 2131165666;
			
			// aapt resource value: 0x7f0701e3
			public const int mango_orange = 2131165667;
			
			// aapt resource value: 0x7f0701e4
			public const int mango_tango = 2131165668;
			
			// aapt resource value: 0x7f0701e5
			public const int mantis = 2131165669;
			
			// aapt resource value: 0x7f0701e6
			public const int marble_blue = 2131165670;
			
			// aapt resource value: 0x7f0701e7
			public const int maroon = 2131165671;
			
			// aapt resource value: 0x7f0701e8
			public const int mascaw_blue_green = 2131165672;
			
			// aapt resource value: 0x7f0701e9
			public const int mauve = 2131165673;
			
			// aapt resource value: 0x7f0701ea
			public const int mauvelous = 2131165674;
			
			// aapt resource value: 0x7f0701eb
			public const int maya_blue = 2131165675;
			
			// aapt resource value: 0x7f0701ec
			public const int meat_brown = 2131165676;
			
			// aapt resource value: 0x7f0701ed
			public const int medium_aquamarine = 2131165677;
			
			// aapt resource value: 0x7f0701ee
			public const int medium_blue = 2131165678;
			
			// aapt resource value: 0x7f0701ef
			public const int medium_candy_apple_red = 2131165679;
			
			// aapt resource value: 0x7f0701f0
			public const int medium_champagne = 2131165680;
			
			// aapt resource value: 0x7f0701f1
			public const int medium_electric_blue = 2131165681;
			
			// aapt resource value: 0x7f0701f2
			public const int medium_forest_green = 2131165682;
			
			// aapt resource value: 0x7f0701f3
			public const int medium_jungle_green = 2131165683;
			
			// aapt resource value: 0x7f0701f4
			public const int medium_lavender_magenta = 2131165684;
			
			// aapt resource value: 0x7f0701f5
			public const int medium_orchid = 2131165685;
			
			// aapt resource value: 0x7f0701f6
			public const int medium_persian_blue = 2131165686;
			
			// aapt resource value: 0x7f0701f7
			public const int medium_purple = 2131165687;
			
			// aapt resource value: 0x7f0701f8
			public const int medium_red_violet = 2131165688;
			
			// aapt resource value: 0x7f0701f9
			public const int medium_sea_green = 2131165689;
			
			// aapt resource value: 0x7f0701fa
			public const int medium_slate_blue = 2131165690;
			
			// aapt resource value: 0x7f0701fb
			public const int medium_spring_bud = 2131165691;
			
			// aapt resource value: 0x7f0701fc
			public const int medium_spring_green = 2131165692;
			
			// aapt resource value: 0x7f0701fd
			public const int medium_taupe = 2131165693;
			
			// aapt resource value: 0x7f0701fe
			public const int medium_teal_blue = 2131165694;
			
			// aapt resource value: 0x7f0701ff
			public const int medium_turquoise = 2131165695;
			
			// aapt resource value: 0x7f070200
			public const int medium_violet_red = 2131165696;
			
			// aapt resource value: 0x7f070201
			public const int melon = 2131165697;
			
			// aapt resource value: 0x7f070202
			public const int metallic_silver = 2131165698;
			
			// aapt resource value: 0x7f070203
			public const int midnight = 2131165699;
			
			// aapt resource value: 0x7f070204
			public const int midnight_blue = 2131165700;
			
			// aapt resource value: 0x7f070205
			public const int midnight_green = 2131165701;
			
			// aapt resource value: 0x7f070206
			public const int mikado_yellow = 2131165702;
			
			// aapt resource value: 0x7f070207
			public const int milk_white = 2131165703;
			
			// aapt resource value: 0x7f070208
			public const int mint = 2131165704;
			
			// aapt resource value: 0x7f070209
			public const int mint_cream = 2131165705;
			
			// aapt resource value: 0x7f07020a
			public const int mint_green = 2131165706;
			
			// aapt resource value: 0x7f07020b
			public const int mist_blue = 2131165707;
			
			// aapt resource value: 0x7f07020c
			public const int misty_rose = 2131165708;
			
			// aapt resource value: 0x7f07020d
			public const int moccasin = 2131165709;
			
			// aapt resource value: 0x7f07020e
			public const int mocha = 2131165710;
			
			// aapt resource value: 0x7f07020f
			public const int moonstone_blue = 2131165711;
			
			// aapt resource value: 0x7f070210
			public const int mordant_red_19 = 2131165712;
			
			// aapt resource value: 0x7f070211
			public const int moss_green = 2131165713;
			
			// aapt resource value: 0x7f070212
			public const int mountain_meadow = 2131165714;
			
			// aapt resource value: 0x7f070213
			public const int mountbatten_pink = 2131165715;
			
			// aapt resource value: 0x7f070214
			public const int msu_green = 2131165716;
			
			// aapt resource value: 0x7f070215
			public const int mulberry = 2131165717;
			
			// aapt resource value: 0x7f070216
			public const int mustard = 2131165718;
			
			// aapt resource value: 0x7f070217
			public const int myrtle = 2131165719;
			
			// aapt resource value: 0x7f070218
			public const int nadeshiko_pink = 2131165720;
			
			// aapt resource value: 0x7f070219
			public const int napier_green = 2131165721;
			
			// aapt resource value: 0x7f07021a
			public const int naples_yellow = 2131165722;
			
			// aapt resource value: 0x7f07021b
			public const int navajo_white = 2131165723;
			
			// aapt resource value: 0x7f07021c
			public const int navy_blue = 2131165724;
			
			// aapt resource value: 0x7f07021d
			public const int nebula_green = 2131165725;
			
			// aapt resource value: 0x7f07021e
			public const int neon_carrot = 2131165726;
			
			// aapt resource value: 0x7f07021f
			public const int neon_fuchsia = 2131165727;
			
			// aapt resource value: 0x7f070220
			public const int neon_green = 2131165728;
			
			// aapt resource value: 0x7f070221
			public const int neon_pink = 2131165729;
			
			// aapt resource value: 0x7f070222
			public const int non_photo_blue = 2131165730;
			
			// aapt resource value: 0x7f070223
			public const int north_texas_green = 2131165731;
			
			// aapt resource value: 0x7f070224
			public const int northern_lights_blue = 2131165732;
			
			// aapt resource value: 0x7f070225
			public const int oak_brown = 2131165733;
			
			// aapt resource value: 0x7f070226
			public const int ocean_blue = 2131165734;
			
			// aapt resource value: 0x7f070227
			public const int ocean_boat_blue = 2131165735;
			
			// aapt resource value: 0x7f070228
			public const int ochre = 2131165736;
			
			// aapt resource value: 0x7f070229
			public const int office_green = 2131165737;
			
			// aapt resource value: 0x7f07022a
			public const int oil = 2131165738;
			
			// aapt resource value: 0x7f07022b
			public const int old_gold = 2131165739;
			
			// aapt resource value: 0x7f07022c
			public const int old_lace = 2131165740;
			
			// aapt resource value: 0x7f07022d
			public const int old_lavender = 2131165741;
			
			// aapt resource value: 0x7f07022e
			public const int old_mauve = 2131165742;
			
			// aapt resource value: 0x7f07022f
			public const int old_rose = 2131165743;
			
			// aapt resource value: 0x7f070230
			public const int olive = 2131165744;
			
			// aapt resource value: 0x7f070231
			public const int olive_drab = 2131165745;
			
			// aapt resource value: 0x7f070232
			public const int olive_green = 2131165746;
			
			// aapt resource value: 0x7f070233
			public const int olivine = 2131165747;
			
			// aapt resource value: 0x7f070234
			public const int onyx = 2131165748;
			
			// aapt resource value: 0x7f070235
			public const int opera_mauve = 2131165749;
			
			// aapt resource value: 0x7f070236
			public const int orange = 2131165750;
			
			// aapt resource value: 0x7f070237
			public const int orange_peel = 2131165751;
			
			// aapt resource value: 0x7f070238
			public const int orange_red = 2131165752;
			
			// aapt resource value: 0x7f070239
			public const int orange_salmon = 2131165753;
			
			// aapt resource value: 0x7f07023a
			public const int orange_yellow = 2131165754;
			
			// aapt resource value: 0x7f07023b
			public const int orchid = 2131165755;
			
			// aapt resource value: 0x7f07023c
			public const int outer_space = 2131165756;
			
			// aapt resource value: 0x7f07023d
			public const int outrageous_orange = 2131165757;
			
			// aapt resource value: 0x7f07023e
			public const int oxford_blue = 2131165758;
			
			// aapt resource value: 0x7f07023f
			public const int pacific_blue = 2131165759;
			
			// aapt resource value: 0x7f070240
			public const int pakistan_green = 2131165760;
			
			// aapt resource value: 0x7f070241
			public const int palatinate_blue = 2131165761;
			
			// aapt resource value: 0x7f070242
			public const int palatinate_purple = 2131165762;
			
			// aapt resource value: 0x7f070243
			public const int pale_aqua = 2131165763;
			
			// aapt resource value: 0x7f070244
			public const int pale_blue = 2131165764;
			
			// aapt resource value: 0x7f070245
			public const int pale_blue_lily = 2131165765;
			
			// aapt resource value: 0x7f070246
			public const int pale_brown = 2131165766;
			
			// aapt resource value: 0x7f070247
			public const int pale_carmine = 2131165767;
			
			// aapt resource value: 0x7f070248
			public const int pale_cerulean = 2131165768;
			
			// aapt resource value: 0x7f070249
			public const int pale_chestnut = 2131165769;
			
			// aapt resource value: 0x7f07024a
			public const int pale_copper = 2131165770;
			
			// aapt resource value: 0x7f07024b
			public const int pale_cornflower_blue = 2131165771;
			
			// aapt resource value: 0x7f07024c
			public const int pale_gold = 2131165772;
			
			// aapt resource value: 0x7f07024d
			public const int pale_goldenrod = 2131165773;
			
			// aapt resource value: 0x7f07024e
			public const int pale_green = 2131165774;
			
			// aapt resource value: 0x7f07024f
			public const int pale_lavender = 2131165775;
			
			// aapt resource value: 0x7f070250
			public const int pale_magenta = 2131165776;
			
			// aapt resource value: 0x7f070251
			public const int pale_pink = 2131165777;
			
			// aapt resource value: 0x7f070252
			public const int pale_red_violet = 2131165778;
			
			// aapt resource value: 0x7f070253
			public const int pale_robin_egg_blue = 2131165779;
			
			// aapt resource value: 0x7f070254
			public const int pale_silver = 2131165780;
			
			// aapt resource value: 0x7f070255
			public const int pale_spring_bud = 2131165781;
			
			// aapt resource value: 0x7f070256
			public const int pale_taupe = 2131165782;
			
			// aapt resource value: 0x7f070257
			public const int pansy_purple = 2131165783;
			
			// aapt resource value: 0x7f070258
			public const int papaya_orange = 2131165784;
			
			// aapt resource value: 0x7f070259
			public const int papaya_whip = 2131165785;
			
			// aapt resource value: 0x7f07025a
			public const int parchment = 2131165786;
			
			// aapt resource value: 0x7f07025b
			public const int paris_green = 2131165787;
			
			// aapt resource value: 0x7f07025c
			public const int pastel_blue = 2131165788;
			
			// aapt resource value: 0x7f07025d
			public const int pastel_brown = 2131165789;
			
			// aapt resource value: 0x7f07025e
			public const int pastel_gray = 2131165790;
			
			// aapt resource value: 0x7f07025f
			public const int pastel_green = 2131165791;
			
			// aapt resource value: 0x7f070260
			public const int pastel_magenta = 2131165792;
			
			// aapt resource value: 0x7f070261
			public const int pastel_orange = 2131165793;
			
			// aapt resource value: 0x7f070262
			public const int pastel_pink = 2131165794;
			
			// aapt resource value: 0x7f070263
			public const int pastel_purple = 2131165795;
			
			// aapt resource value: 0x7f070264
			public const int pastel_red = 2131165796;
			
			// aapt resource value: 0x7f070265
			public const int pastel_violet = 2131165797;
			
			// aapt resource value: 0x7f070266
			public const int pastel_yellow = 2131165798;
			
			// aapt resource value: 0x7f070267
			public const int payne_grey = 2131165799;
			
			// aapt resource value: 0x7f070268
			public const int peach = 2131165800;
			
			// aapt resource value: 0x7f070269
			public const int peach_puff = 2131165801;
			
			// aapt resource value: 0x7f07026a
			public const int peach_yellow = 2131165802;
			
			// aapt resource value: 0x7f07026b
			public const int pearl = 2131165803;
			
			// aapt resource value: 0x7f07026c
			public const int pearl_aqua = 2131165804;
			
			// aapt resource value: 0x7f07026d
			public const int peridot = 2131165805;
			
			// aapt resource value: 0x7f07026e
			public const int persian_blue = 2131165806;
			
			// aapt resource value: 0x7f07026f
			public const int persian_indigo = 2131165807;
			
			// aapt resource value: 0x7f070270
			public const int persian_orange = 2131165808;
			
			// aapt resource value: 0x7f070271
			public const int persian_pink = 2131165809;
			
			// aapt resource value: 0x7f070272
			public const int persian_plum = 2131165810;
			
			// aapt resource value: 0x7f070273
			public const int persian_red = 2131165811;
			
			// aapt resource value: 0x7f070274
			public const int persian_rose = 2131165812;
			
			// aapt resource value: 0x7f070275
			public const int phthalo_blue = 2131165813;
			
			// aapt resource value: 0x7f070276
			public const int phthalo_green = 2131165814;
			
			// aapt resource value: 0x7f070277
			public const int pig_pink = 2131165815;
			
			// aapt resource value: 0x7f070278
			public const int piggy_pink = 2131165816;
			
			// aapt resource value: 0x7f070279
			public const int pine_green = 2131165817;
			
			// aapt resource value: 0x7f07027a
			public const int pink = 2131165818;
			
			// aapt resource value: 0x7f07027b
			public const int pink_bow = 2131165819;
			
			// aapt resource value: 0x7f07027c
			public const int pink_bubblegum = 2131165820;
			
			// aapt resource value: 0x7f07027d
			public const int pink_cupcake = 2131165821;
			
			// aapt resource value: 0x7f07027e
			public const int pink_daisy = 2131165822;
			
			// aapt resource value: 0x7f07027f
			public const int pink_flamingo = 2131165823;
			
			// aapt resource value: 0x7f070280
			public const int pink_lemonade = 2131165824;
			
			// aapt resource value: 0x7f070281
			public const int pink_pearl = 2131165825;
			
			// aapt resource value: 0x7f070282
			public const int pink_rose = 2131165826;
			
			// aapt resource value: 0x7f070283
			public const int pink_sherbet = 2131165827;
			
			// aapt resource value: 0x7f070284
			public const int pistachio = 2131165828;
			
			// aapt resource value: 0x7f070285
			public const int pistachio_green = 2131165829;
			
			// aapt resource value: 0x7f070286
			public const int platinum = 2131165830;
			
			// aapt resource value: 0x7f070287
			public const int plum = 2131165831;
			
			// aapt resource value: 0x7f070288
			public const int plum_pie = 2131165832;
			
			// aapt resource value: 0x7f070289
			public const int plum_purple = 2131165833;
			
			// aapt resource value: 0x7f07028a
			public const int plum_velvet = 2131165834;
			
			// aapt resource value: 0x7f07028b
			public const int portland_orange = 2131165835;
			
			// aapt resource value: 0x7f07028c
			public const int powder_blue = 2131165836;
			
			// aapt resource value: 0x7f07028d
			public const int princeton_orange = 2131165837;
			
			// aapt resource value: 0x7f07028e
			public const int prussian_blue = 2131165838;
			
			// aapt resource value: 0x7f07028f
			public const int psychedelic_purple = 2131165839;
			
			// aapt resource value: 0x7f070290
			public const int puce = 2131165840;
			
			// aapt resource value: 0x7f070291
			public const int pumpkin = 2131165841;
			
			// aapt resource value: 0x7f070292
			public const int pumpkin_orange = 2131165842;
			
			// aapt resource value: 0x7f070293
			public const int purple = 2131165843;
			
			// aapt resource value: 0x7f070294
			public const int purple_amethyst = 2131165844;
			
			// aapt resource value: 0x7f070295
			public const int purple_daffodil = 2131165845;
			
			// aapt resource value: 0x7f070296
			public const int purple_dragon = 2131165846;
			
			// aapt resource value: 0x7f070297
			public const int purple_flower = 2131165847;
			
			// aapt resource value: 0x7f070298
			public const int purple_haze = 2131165848;
			
			// aapt resource value: 0x7f070299
			public const int purple_heart = 2131165849;
			
			// aapt resource value: 0x7f07029a
			public const int purple_iris = 2131165850;
			
			// aapt resource value: 0x7f07029b
			public const int purple_jam = 2131165851;
			
			// aapt resource value: 0x7f07029c
			public const int purple_mimosa = 2131165852;
			
			// aapt resource value: 0x7f07029d
			public const int purple_monster = 2131165853;
			
			// aapt resource value: 0x7f07029e
			public const int purple_mountain_majesty = 2131165854;
			
			// aapt resource value: 0x7f07029f
			public const int purple_pizzazz = 2131165855;
			
			// aapt resource value: 0x7f0702a0
			public const int purple_sage_bush = 2131165856;
			
			// aapt resource value: 0x7f0702a1
			public const int purple_taupe = 2131165857;
			
			// aapt resource value: 0x7f0702a2
			public const int radical_red = 2131165858;
			
			// aapt resource value: 0x7f0702a3
			public const int raspberry = 2131165859;
			
			// aapt resource value: 0x7f0702a4
			public const int raspberry_glace = 2131165860;
			
			// aapt resource value: 0x7f0702a5
			public const int raspberry_pink = 2131165861;
			
			// aapt resource value: 0x7f0702a6
			public const int raspberry_rose = 2131165862;
			
			// aapt resource value: 0x7f0702a7
			public const int raw_sienna = 2131165863;
			
			// aapt resource value: 0x7f0702a8
			public const int razzle_dazzle_rose = 2131165864;
			
			// aapt resource value: 0x7f0702a9
			public const int razzmatazz = 2131165865;
			
			// aapt resource value: 0x7f0702aa
			public const int red = 2131165866;
			
			// aapt resource value: 0x7f0702ab
			public const int red_brown = 2131165867;
			
			// aapt resource value: 0x7f0702ac
			public const int red_dirt = 2131165868;
			
			// aapt resource value: 0x7f0702ad
			public const int red_fox = 2131165869;
			
			// aapt resource value: 0x7f0702ae
			public const int red_orange = 2131165870;
			
			// aapt resource value: 0x7f0702af
			public const int red_violet = 2131165871;
			
			// aapt resource value: 0x7f0702b0
			public const int red_wine = 2131165872;
			
			// aapt resource value: 0x7f0702b1
			public const int rich_black = 2131165873;
			
			// aapt resource value: 0x7f0702b2
			public const int rich_carmine = 2131165874;
			
			// aapt resource value: 0x7f0702b3
			public const int rich_electric_blue = 2131165875;
			
			// aapt resource value: 0x7f0702b4
			public const int rich_lilac = 2131165876;
			
			// aapt resource value: 0x7f0702b5
			public const int rich_maroon = 2131165877;
			
			// aapt resource value: 0x7f0702b6
			public const int rifle_green = 2131165878;
			
			// aapt resource value: 0x7f0702b7
			public const int robin_egg_blue = 2131165879;
			
			// aapt resource value: 0x7f0702b8
			public const int rogue_pink = 2131165880;
			
			// aapt resource value: 0x7f0702b9
			public const int rose = 2131165881;
			
			// aapt resource value: 0x7f0702ba
			public const int rose_bonbon = 2131165882;
			
			// aapt resource value: 0x7f0702bb
			public const int rose_ebony = 2131165883;
			
			// aapt resource value: 0x7f0702bc
			public const int rose_gold = 2131165884;
			
			// aapt resource value: 0x7f0702bd
			public const int rose_madder = 2131165885;
			
			// aapt resource value: 0x7f0702be
			public const int rose_pink = 2131165886;
			
			// aapt resource value: 0x7f0702bf
			public const int rose_quartz = 2131165887;
			
			// aapt resource value: 0x7f0702c0
			public const int rose_taupe = 2131165888;
			
			// aapt resource value: 0x7f0702c1
			public const int rose_vale = 2131165889;
			
			// aapt resource value: 0x7f0702c2
			public const int rosewood = 2131165890;
			
			// aapt resource value: 0x7f0702c3
			public const int rosso_corsa = 2131165891;
			
			// aapt resource value: 0x7f0702c4
			public const int rosy_brown = 2131165892;
			
			// aapt resource value: 0x7f0702c5
			public const int rosy_finch = 2131165893;
			
			// aapt resource value: 0x7f0702c6
			public const int royal_azure = 2131165894;
			
			// aapt resource value: 0x7f0702c7
			public const int royal_blue = 2131165895;
			
			// aapt resource value: 0x7f0702c8
			public const int royal_fuchsia = 2131165896;
			
			// aapt resource value: 0x7f0702c9
			public const int royal_purple = 2131165897;
			
			// aapt resource value: 0x7f0702ca
			public const int rubber_ducky_yellow = 2131165898;
			
			// aapt resource value: 0x7f0702cb
			public const int ruby = 2131165899;
			
			// aapt resource value: 0x7f0702cc
			public const int ruby_red = 2131165900;
			
			// aapt resource value: 0x7f0702cd
			public const int ruddy = 2131165901;
			
			// aapt resource value: 0x7f0702ce
			public const int ruddy_brown = 2131165902;
			
			// aapt resource value: 0x7f0702cf
			public const int ruddy_pink = 2131165903;
			
			// aapt resource value: 0x7f0702d0
			public const int rufous = 2131165904;
			
			// aapt resource value: 0x7f0702d1
			public const int russet = 2131165905;
			
			// aapt resource value: 0x7f0702d2
			public const int rust = 2131165906;
			
			// aapt resource value: 0x7f0702d3
			public const int sacramento_state_green = 2131165907;
			
			// aapt resource value: 0x7f0702d4
			public const int saddle_brown = 2131165908;
			
			// aapt resource value: 0x7f0702d5
			public const int safety_orange = 2131165909;
			
			// aapt resource value: 0x7f0702d6
			public const int saffron = 2131165910;
			
			// aapt resource value: 0x7f0702d7
			public const int saint_patrick_blue = 2131165911;
			
			// aapt resource value: 0x7f0702d8
			public const int salad_green = 2131165912;
			
			// aapt resource value: 0x7f0702d9
			public const int salmon = 2131165913;
			
			// aapt resource value: 0x7f0702da
			public const int salmon_pink = 2131165914;
			
			// aapt resource value: 0x7f0702db
			public const int sand = 2131165915;
			
			// aapt resource value: 0x7f0702dc
			public const int sandstone = 2131165916;
			
			// aapt resource value: 0x7f0702dd
			public const int sandstorm = 2131165917;
			
			// aapt resource value: 0x7f0702de
			public const int sandy_brown = 2131165918;
			
			// aapt resource value: 0x7f0702df
			public const int sandy_taupe = 2131165919;
			
			// aapt resource value: 0x7f0702e0
			public const int sangria = 2131165920;
			
			// aapt resource value: 0x7f0702e1
			public const int sap_green = 2131165921;
			
			// aapt resource value: 0x7f0702e2
			public const int sapphire = 2131165922;
			
			// aapt resource value: 0x7f0702e3
			public const int sapphire_blue = 2131165923;
			
			// aapt resource value: 0x7f0702e4
			public const int satin_sheen_gold = 2131165924;
			
			// aapt resource value: 0x7f0702e5
			public const int scarlet = 2131165925;
			
			// aapt resource value: 0x7f0702e6
			public const int school_bus_yellow = 2131165926;
			
			// aapt resource value: 0x7f0702e7
			public const int screamin_green = 2131165927;
			
			// aapt resource value: 0x7f0702e8
			public const int sea_blue = 2131165928;
			
			// aapt resource value: 0x7f0702e9
			public const int sea_green = 2131165929;
			
			// aapt resource value: 0x7f0702ea
			public const int sea_turtle_green = 2131165930;
			
			// aapt resource value: 0x7f0702eb
			public const int seal_brown = 2131165931;
			
			// aapt resource value: 0x7f0702ec
			public const int seashell = 2131165932;
			
			// aapt resource value: 0x7f0702ed
			public const int seaweed_green = 2131165933;
			
			// aapt resource value: 0x7f0702ee
			public const int sedona = 2131165934;
			
			// aapt resource value: 0x7f0702ef
			public const int selective_yellow = 2131165935;
			
			// aapt resource value: 0x7f0702f0
			public const int sepia = 2131165936;
			
			// aapt resource value: 0x7f0702f1
			public const int shadow = 2131165937;
			
			// aapt resource value: 0x7f0702f2
			public const int shamrock = 2131165938;
			
			// aapt resource value: 0x7f0702f3
			public const int shamrock_green = 2131165939;
			
			// aapt resource value: 0x7f0702f4
			public const int shocking_orange = 2131165940;
			
			// aapt resource value: 0x7f0702f5
			public const int shocking_pink = 2131165941;
			
			// aapt resource value: 0x7f0702f6
			public const int sienna = 2131165942;
			
			// aapt resource value: 0x7f0702f7
			public const int silk_blue = 2131165943;
			
			// aapt resource value: 0x7f0702f8
			public const int silver = 2131165944;
			
			// aapt resource value: 0x7f0702f9
			public const int sinopia = 2131165945;
			
			// aapt resource value: 0x7f0702fa
			public const int skobeloff = 2131165946;
			
			// aapt resource value: 0x7f0702fb
			public const int sky_blue = 2131165947;
			
			// aapt resource value: 0x7f0702fc
			public const int sky_magenta = 2131165948;
			
			// aapt resource value: 0x7f0702fd
			public const int slate_blue = 2131165949;
			
			// aapt resource value: 0x7f0702fe
			public const int slate_gray = 2131165950;
			
			// aapt resource value: 0x7f0702ff
			public const int slime_green = 2131165951;
			
			// aapt resource value: 0x7f070300
			public const int smokey_gray = 2131165952;
			
			// aapt resource value: 0x7f070301
			public const int smokey_topaz = 2131165953;
			
			// aapt resource value: 0x7f070302
			public const int smoky_black = 2131165954;
			
			// aapt resource value: 0x7f070303
			public const int snow = 2131165955;
			
			// aapt resource value: 0x7f070304
			public const int spiro_disco_ball = 2131165956;
			
			// aapt resource value: 0x7f070305
			public const int spring_bud = 2131165957;
			
			// aapt resource value: 0x7f070306
			public const int spring_green = 2131165958;
			
			// aapt resource value: 0x7f070307
			public const int steel_blue = 2131165959;
			
			// aapt resource value: 0x7f070308
			public const int stil_de_grain_yellow = 2131165960;
			
			// aapt resource value: 0x7f070309
			public const int stoplight_go_green = 2131165961;
			
			// aapt resource value: 0x7f07030a
			public const int straw = 2131165962;
			
			// aapt resource value: 0x7f07030b
			public const int sun_yellow = 2131165963;
			
			// aapt resource value: 0x7f07030c
			public const int sunglow = 2131165964;
			
			// aapt resource value: 0x7f07030d
			public const int sunrise_orange = 2131165965;
			
			// aapt resource value: 0x7f07030e
			public const int sunset = 2131165966;
			
			// aapt resource value: 0x7f07030f
			public const int sunset_orange = 2131165967;
			
			// aapt resource value: 0x7f070310
			public const int tan = 2131165968;
			
			// aapt resource value: 0x7f070311
			public const int tan_brown = 2131165969;
			
			// aapt resource value: 0x7f070312
			public const int tangelo = 2131165970;
			
			// aapt resource value: 0x7f070313
			public const int tangerine = 2131165971;
			
			// aapt resource value: 0x7f070314
			public const int tangerine_yellow = 2131165972;
			
			// aapt resource value: 0x7f070315
			public const int taupe = 2131165973;
			
			// aapt resource value: 0x7f070316
			public const int taupe_gray = 2131165974;
			
			// aapt resource value: 0x7f070317
			public const int tawny = 2131165975;
			
			// aapt resource value: 0x7f070318
			public const int tea_green = 2131165976;
			
			// aapt resource value: 0x7f070319
			public const int tea_rose = 2131165977;
			
			// aapt resource value: 0x7f07031a
			public const int teal = 2131165978;
			
			// aapt resource value: 0x7f07031b
			public const int teal_blue = 2131165979;
			
			// aapt resource value: 0x7f07031c
			public const int teal_green = 2131165980;
			
			// aapt resource value: 0x7f07031d
			public const int terra_cotta = 2131165981;
			
			// aapt resource value: 0x7f07031e
			public const int thistle = 2131165982;
			
			// aapt resource value: 0x7f07031f
			public const int thulian_pink = 2131165983;
			
			// aapt resource value: 0x7f070320
			public const int tickle_me_pink = 2131165984;
			
			// aapt resource value: 0x7f070321
			public const int tiffany_blue = 2131165985;
			
			// aapt resource value: 0x7f070322
			public const int tiger_eye = 2131165986;
			
			// aapt resource value: 0x7f070323
			public const int tiger_orange = 2131165987;
			
			// aapt resource value: 0x7f070324
			public const int timberwolf = 2131165988;
			
			// aapt resource value: 0x7f070325
			public const int titanium_yellow = 2131165989;
			
			// aapt resource value: 0x7f070326
			public const int tomato = 2131165990;
			
			// aapt resource value: 0x7f070327
			public const int toolbox = 2131165991;
			
			// aapt resource value: 0x7f070328
			public const int topaz = 2131165992;
			
			// aapt resource value: 0x7f070329
			public const int tractor_red = 2131165993;
			
			// aapt resource value: 0x7f070372
			public const int transparent_black_hex_1 = 2131166066;
			
			// aapt resource value: 0x7f07037b
			public const int transparent_black_hex_10 = 2131166075;
			
			// aapt resource value: 0x7f07037c
			public const int transparent_black_hex_11 = 2131166076;
			
			// aapt resource value: 0x7f07037d
			public const int transparent_black_hex_12 = 2131166077;
			
			// aapt resource value: 0x7f07037e
			public const int transparent_black_hex_13 = 2131166078;
			
			// aapt resource value: 0x7f07037f
			public const int transparent_black_hex_14 = 2131166079;
			
			// aapt resource value: 0x7f070380
			public const int transparent_black_hex_15 = 2131166080;
			
			// aapt resource value: 0x7f070373
			public const int transparent_black_hex_2 = 2131166067;
			
			// aapt resource value: 0x7f070374
			public const int transparent_black_hex_3 = 2131166068;
			
			// aapt resource value: 0x7f070375
			public const int transparent_black_hex_4 = 2131166069;
			
			// aapt resource value: 0x7f070376
			public const int transparent_black_hex_5 = 2131166070;
			
			// aapt resource value: 0x7f070377
			public const int transparent_black_hex_6 = 2131166071;
			
			// aapt resource value: 0x7f070378
			public const int transparent_black_hex_7 = 2131166072;
			
			// aapt resource value: 0x7f070379
			public const int transparent_black_hex_8 = 2131166073;
			
			// aapt resource value: 0x7f07037a
			public const int transparent_black_hex_9 = 2131166074;
			
			// aapt resource value: 0x7f070382
			public const int transparent_black_percent_10 = 2131166082;
			
			// aapt resource value: 0x7f070383
			public const int transparent_black_percent_15 = 2131166083;
			
			// aapt resource value: 0x7f070384
			public const int transparent_black_percent_20 = 2131166084;
			
			// aapt resource value: 0x7f070385
			public const int transparent_black_percent_25 = 2131166085;
			
			// aapt resource value: 0x7f070386
			public const int transparent_black_percent_30 = 2131166086;
			
			// aapt resource value: 0x7f070387
			public const int transparent_black_percent_35 = 2131166087;
			
			// aapt resource value: 0x7f070388
			public const int transparent_black_percent_40 = 2131166088;
			
			// aapt resource value: 0x7f070389
			public const int transparent_black_percent_45 = 2131166089;
			
			// aapt resource value: 0x7f070381
			public const int transparent_black_percent_5 = 2131166081;
			
			// aapt resource value: 0x7f07038a
			public const int transparent_black_percent_50 = 2131166090;
			
			// aapt resource value: 0x7f07038b
			public const int transparent_black_percent_55 = 2131166091;
			
			// aapt resource value: 0x7f07038c
			public const int transparent_black_percent_60 = 2131166092;
			
			// aapt resource value: 0x7f07038d
			public const int transparent_black_percent_65 = 2131166093;
			
			// aapt resource value: 0x7f07038e
			public const int transparent_black_percent_70 = 2131166094;
			
			// aapt resource value: 0x7f07038f
			public const int transparent_black_percent_75 = 2131166095;
			
			// aapt resource value: 0x7f070390
			public const int transparent_black_percent_80 = 2131166096;
			
			// aapt resource value: 0x7f070391
			public const int transparent_black_percent_85 = 2131166097;
			
			// aapt resource value: 0x7f070392
			public const int transparent_black_percent_90 = 2131166098;
			
			// aapt resource value: 0x7f070393
			public const int transparent_black_percent_95 = 2131166099;
			
			// aapt resource value: 0x7f070394
			public const int transparent_white_hex_1 = 2131166100;
			
			// aapt resource value: 0x7f07039d
			public const int transparent_white_hex_10 = 2131166109;
			
			// aapt resource value: 0x7f07039e
			public const int transparent_white_hex_11 = 2131166110;
			
			// aapt resource value: 0x7f07039f
			public const int transparent_white_hex_12 = 2131166111;
			
			// aapt resource value: 0x7f0703a0
			public const int transparent_white_hex_13 = 2131166112;
			
			// aapt resource value: 0x7f0703a1
			public const int transparent_white_hex_14 = 2131166113;
			
			// aapt resource value: 0x7f0703a2
			public const int transparent_white_hex_15 = 2131166114;
			
			// aapt resource value: 0x7f070395
			public const int transparent_white_hex_2 = 2131166101;
			
			// aapt resource value: 0x7f070396
			public const int transparent_white_hex_3 = 2131166102;
			
			// aapt resource value: 0x7f070397
			public const int transparent_white_hex_4 = 2131166103;
			
			// aapt resource value: 0x7f070398
			public const int transparent_white_hex_5 = 2131166104;
			
			// aapt resource value: 0x7f070399
			public const int transparent_white_hex_6 = 2131166105;
			
			// aapt resource value: 0x7f07039a
			public const int transparent_white_hex_7 = 2131166106;
			
			// aapt resource value: 0x7f07039b
			public const int transparent_white_hex_8 = 2131166107;
			
			// aapt resource value: 0x7f07039c
			public const int transparent_white_hex_9 = 2131166108;
			
			// aapt resource value: 0x7f0703a4
			public const int transparent_white_percent_10 = 2131166116;
			
			// aapt resource value: 0x7f0703a5
			public const int transparent_white_percent_15 = 2131166117;
			
			// aapt resource value: 0x7f0703a6
			public const int transparent_white_percent_20 = 2131166118;
			
			// aapt resource value: 0x7f0703a7
			public const int transparent_white_percent_25 = 2131166119;
			
			// aapt resource value: 0x7f0703a8
			public const int transparent_white_percent_30 = 2131166120;
			
			// aapt resource value: 0x7f0703a9
			public const int transparent_white_percent_35 = 2131166121;
			
			// aapt resource value: 0x7f0703aa
			public const int transparent_white_percent_40 = 2131166122;
			
			// aapt resource value: 0x7f0703ab
			public const int transparent_white_percent_45 = 2131166123;
			
			// aapt resource value: 0x7f0703a3
			public const int transparent_white_percent_5 = 2131166115;
			
			// aapt resource value: 0x7f0703ac
			public const int transparent_white_percent_50 = 2131166124;
			
			// aapt resource value: 0x7f0703ad
			public const int transparent_white_percent_55 = 2131166125;
			
			// aapt resource value: 0x7f0703ae
			public const int transparent_white_percent_60 = 2131166126;
			
			// aapt resource value: 0x7f0703af
			public const int transparent_white_percent_65 = 2131166127;
			
			// aapt resource value: 0x7f0703b0
			public const int transparent_white_percent_70 = 2131166128;
			
			// aapt resource value: 0x7f0703b1
			public const int transparent_white_percent_75 = 2131166129;
			
			// aapt resource value: 0x7f0703b2
			public const int transparent_white_percent_80 = 2131166130;
			
			// aapt resource value: 0x7f0703b3
			public const int transparent_white_percent_85 = 2131166131;
			
			// aapt resource value: 0x7f0703b4
			public const int transparent_white_percent_90 = 2131166132;
			
			// aapt resource value: 0x7f0703b5
			public const int transparent_white_percent_95 = 2131166133;
			
			// aapt resource value: 0x7f07032a
			public const int tron_blue = 2131165994;
			
			// aapt resource value: 0x7f07032b
			public const int tropical_rain_forest = 2131165995;
			
			// aapt resource value: 0x7f07032c
			public const int true_blue = 2131165996;
			
			// aapt resource value: 0x7f07032d
			public const int tufts_blue = 2131165997;
			
			// aapt resource value: 0x7f07032e
			public const int tulip_pink = 2131165998;
			
			// aapt resource value: 0x7f07032f
			public const int tumbleweed = 2131165999;
			
			// aapt resource value: 0x7f070330
			public const int turkish_rose = 2131166000;
			
			// aapt resource value: 0x7f070331
			public const int turquoise = 2131166001;
			
			// aapt resource value: 0x7f070332
			public const int turquoise_blue = 2131166002;
			
			// aapt resource value: 0x7f070333
			public const int turquoise_green = 2131166003;
			
			// aapt resource value: 0x7f070334
			public const int tuscan_red = 2131166004;
			
			// aapt resource value: 0x7f070335
			public const int twilight_lavender = 2131166005;
			
			// aapt resource value: 0x7f070336
			public const int tyrian_purple = 2131166006;
			
			// aapt resource value: 0x7f070337
			public const int ua_blue = 2131166007;
			
			// aapt resource value: 0x7f070338
			public const int ua_red = 2131166008;
			
			// aapt resource value: 0x7f070339
			public const int ube = 2131166009;
			
			// aapt resource value: 0x7f07033a
			public const int ucla_blue = 2131166010;
			
			// aapt resource value: 0x7f07033b
			public const int ucla_gold = 2131166011;
			
			// aapt resource value: 0x7f07033c
			public const int ufo_green = 2131166012;
			
			// aapt resource value: 0x7f07033d
			public const int ultra_pink = 2131166013;
			
			// aapt resource value: 0x7f07033e
			public const int ultramarine = 2131166014;
			
			// aapt resource value: 0x7f07033f
			public const int ultramarine_blue = 2131166015;
			
			// aapt resource value: 0x7f070340
			public const int umber = 2131166016;
			
			// aapt resource value: 0x7f070341
			public const int united_nations_blue = 2131166017;
			
			// aapt resource value: 0x7f070342
			public const int university_of_california_gold = 2131166018;
			
			// aapt resource value: 0x7f070343
			public const int unmellow_yellow = 2131166019;
			
			// aapt resource value: 0x7f070344
			public const int up_forest_green = 2131166020;
			
			// aapt resource value: 0x7f070345
			public const int up_maroon = 2131166021;
			
			// aapt resource value: 0x7f070346
			public const int upsdell_red = 2131166022;
			
			// aapt resource value: 0x7f070347
			public const int urobilin = 2131166023;
			
			// aapt resource value: 0x7f070348
			public const int utah_crimson = 2131166024;
			
			// aapt resource value: 0x7f070349
			public const int valentine_red = 2131166025;
			
			// aapt resource value: 0x7f07034a
			public const int vampire_gray = 2131166026;
			
			// aapt resource value: 0x7f07034b
			public const int vanilla = 2131166027;
			
			// aapt resource value: 0x7f07034c
			public const int vegas_gold = 2131166028;
			
			// aapt resource value: 0x7f07034d
			public const int velvet_maroon = 2131166029;
			
			// aapt resource value: 0x7f07034e
			public const int venetian_red = 2131166030;
			
			// aapt resource value: 0x7f07034f
			public const int venom_green = 2131166031;
			
			// aapt resource value: 0x7f070350
			public const int verdigris = 2131166032;
			
			// aapt resource value: 0x7f070351
			public const int veronica = 2131166033;
			
			// aapt resource value: 0x7f070352
			public const int viola_purple = 2131166034;
			
			// aapt resource value: 0x7f070353
			public const int violet = 2131166035;
			
			// aapt resource value: 0x7f070354
			public const int violet_blue = 2131166036;
			
			// aapt resource value: 0x7f070355
			public const int violet_red = 2131166037;
			
			// aapt resource value: 0x7f070356
			public const int viridian = 2131166038;
			
			// aapt resource value: 0x7f070357
			public const int vivid_auburn = 2131166039;
			
			// aapt resource value: 0x7f070358
			public const int vivid_burgundy = 2131166040;
			
			// aapt resource value: 0x7f070359
			public const int vivid_cerise = 2131166041;
			
			// aapt resource value: 0x7f07035a
			public const int vivid_tangerine = 2131166042;
			
			// aapt resource value: 0x7f07035b
			public const int vivid_violet = 2131166043;
			
			// aapt resource value: 0x7f07035c
			public const int warm_black = 2131166044;
			
			// aapt resource value: 0x7f07035d
			public const int water = 2131166045;
			
			// aapt resource value: 0x7f07035e
			public const int watermelon_pink = 2131166046;
			
			// aapt resource value: 0x7f07035f
			public const int wenge = 2131166047;
			
			// aapt resource value: 0x7f070360
			public const int wheat = 2131166048;
			
			// aapt resource value: 0x7f070361
			public const int white = 2131166049;
			
			// aapt resource value: 0x7f070362
			public const int white_smoke = 2131166050;
			
			// aapt resource value: 0x7f070363
			public const int wild_blue_yonder = 2131166051;
			
			// aapt resource value: 0x7f070364
			public const int wild_strawberry = 2131166052;
			
			// aapt resource value: 0x7f070365
			public const int wild_watermelon = 2131166053;
			
			// aapt resource value: 0x7f070366
			public const int wine = 2131166054;
			
			// aapt resource value: 0x7f070367
			public const int wiseria_purple = 2131166055;
			
			// aapt resource value: 0x7f070368
			public const int wisteria = 2131166056;
			
			// aapt resource value: 0x7f070369
			public const int wood = 2131166057;
			
			// aapt resource value: 0x7f07036a
			public const int xanadu = 2131166058;
			
			// aapt resource value: 0x7f07036b
			public const int yale_blue = 2131166059;
			
			// aapt resource value: 0x7f07036c
			public const int yellow = 2131166060;
			
			// aapt resource value: 0x7f07036d
			public const int yellow_green = 2131166061;
			
			// aapt resource value: 0x7f07036e
			public const int yellow_orange = 2131166062;
			
			// aapt resource value: 0x7f07036f
			public const int zaffre = 2131166063;
			
			// aapt resource value: 0x7f070370
			public const int zinnwaldite_brown = 2131166064;
			
			// aapt resource value: 0x7f070371
			public const int zombie_green = 2131166065;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int cardview_compat_inset_shadow = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_elevation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_default_radius = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundMain = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blueButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int borderShape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int greenButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_account_plus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_content_cut = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_delete = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_dots = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_dots_vertical = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_dropbox = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_folder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_magnify = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_microscope = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_pencil = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_plus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_star = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_upload = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int roundButton = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int roundLayout = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int roundShape = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int allButton = 2131099664;
			
			// aapt resource value: 0x7f060030
			public const int delete = 2131099696;
			
			// aapt resource value: 0x7f06001f
			public const int deleteButton = 2131099679;
			
			// aapt resource value: 0x7f06002f
			public const int favorite = 2131099695;
			
			// aapt resource value: 0x7f06001e
			public const int favoriteButton = 2131099678;
			
			// aapt resource value: 0x7f060024
			public const int folderButton = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int help = 2131099690;
			
			// aapt resource value: 0x7f06000e
			public const int imageView1 = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int imageView2 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int imageView3 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int imageView4 = 2131099676;
			
			// aapt resource value: 0x7f060003
			public const int infoText = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int labtest_name = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int labtest_photo = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int labtest_value = 2131099669;
			
			// aapt resource value: 0x7f060008
			public const int layoutPop = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int linearLay = 2131099673;
			
			// aapt resource value: 0x7f060007
			public const int linearList = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int linearList1 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int linearList2 = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int listView = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int listView1 = 2131099666;
			
			// aapt resource value: 0x7f060028
			public const int mainMenu = 2131099688;
			
			// aapt resource value: 0x7f06002d
			public const int menupoint = 2131099693;
			
			// aapt resource value: 0x7f060004
			public const int moreButton = 2131099652;
			
			// aapt resource value: 0x7f060031
			public const int move = 2131099697;
			
			// aapt resource value: 0x7f060020
			public const int moveButton = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int penButton = 2131099685;
			
			// aapt resource value: 0x7f060018
			public const int plusButton = 2131099672;
			
			// aapt resource value: 0x7f06000a
			public const int plusLayout = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int recyclerView = 2131099671;
			
			// aapt resource value: 0x7f060029
			public const int refresh = 2131099689;
			
			// aapt resource value: 0x7f060005
			public const int relativeLay = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int roundButton = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int searchButton = 2131099665;
			
			// aapt resource value: 0x7f06002c
			public const int setting = 2131099692;
			
			// aapt resource value: 0x7f060027
			public const int shape_my = 2131099687;
			
			// aapt resource value: 0x7f06002e
			public const int share = 2131099694;
			
			// aapt resource value: 0x7f06001d
			public const int shareButton = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int textView1 = 2131099663;
			
			// aapt resource value: 0x7f060022
			public const int textView2 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int textView3 = 2131099683;
			
			// aapt resource value: 0x7f06000c
			public const int upLayout = 2131099660;
			
			// aapt resource value: 0x7f06002b
			public const int upgrade = 2131099691;
			
			// aapt resource value: 0x7f060026
			public const int uploadIconbutton = 2131099686;
			
			// aapt resource value: 0x7f060021
			public const int uploadLayoutRelative = 2131099681;
			
			// aapt resource value: 0x7f06000d
			public const int viewMain = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int viewRound = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int viewRound1 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FileLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PhotoLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PhotoLayout1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int plusLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Popup = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int UploadLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int mainmenu = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int menupoint = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CardView_Dark = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Light = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutoScaleTextView = new int[] {
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int AutoScaleTextView_minTextSize = 0;
			
			// aapt resource value: 1
			public const int AutoScaleTextView_shrinkTextSize = 1;
			
			public static int[] CardView = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
